events {}
http {
 server {
  listen 80;
  location / {
  # FIX: was "http://application:3001" but service is "app", port 3000
#    proxy_pass http://application:3001;
    proxy_pass http://app:3000;
  }
 }
}
