apiVersion: apps/v1
kind: Deployment
metadata:
  name: broken-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: broken
  template:
    metadata:
      labels:
        app: broken
    spec:
      containers:
        - name: app
          image: broken-app:local
          # FIX:was command: ["node","index.js"] - no index .js in image, entry point is server.js . This was the actual crsh (CrashLoopBackOff)
          #          command: ["node","index.js"]
          command: ["node","server.js"]
          env:
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: jwt
          livenessProbe:
            httpGet:
              # FIX: was "/live" -route doesn't exit, every probe got 404
              #              path: /live
              path: /health
              port: 3000