# Since deployment.yamlhas already reference this Secret (name: app-secret,key:jwt) , so if we dont hav this secret kubenetes cannot find the secret ad hits CreateContainerConfigError

apiVersion: v1
kind: Secret
metadata:
  name: app-secret
type: Opaque
stringData:
  jwt: " 1234"

