name: Local Minikube Deploy

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: [self-hosted, macOS]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Build app image
        run: docker build -t broken-app:local ./app

      - name: Load image into Minikube
        run: minikube image load broken-app:local

      - name: Apply Kubernetes secret
        run: kubectl apply -f kubernetes/secretcConf.yaml

      - name: Apply Kubernetes deployment
        run: kubectl apply -f kubernetes/deployment.yaml

      - name: Wait for deployment
        run: kubectl rollout status deployment/broken-app --timeout=180s

      - name: Show pod status
        run: kubectl get pods
